### ISSUE TITLE
Unable to load project on ExpoGo

### ISSUE THREAD

**Issue by KYWILS21** [cis3296f24/Locally#32]
I was able to get the QR code to scan with my phone, but when it loaded onto ExpoGi, I was met with a “the request timed out” error 
![IMG_1525](https://github.com/user-attachments/assets/4e3bb93a-aa33-407d-8b82-1acdde6aef8b)
![IMG_1526](https://github.com/user-attachments/assets/09582cff-ad31-4c25-8206-4c31ecc7b121)

**Comment by jaimenguyen168** [comment]
I forgot to mention that you need to be in the same network.
