### ISSUE TITLE
ReadMe Difficult to interpret and Google Map API Key, login twice

### ISSUE THREAD

**Issue by PeterLy2** [cis3296f24/Locally#34]
The read me was quite difficult to go through. It would be easier for a user if you went step by step through it. For example in the installation instructions you said from the root directory to run this command cd .\locally-app\ but when we clone we are in the root folder but when we copy paste that command it doesn't work. the command should be cd locally-app. Also when making the API key the read me should give more step by step instructions to how to get the API key as the user usually doesn't know what they are doing. When they create a project they are put on a screen that doesn't have the "Enable: Maps SDK (Android & iOS) and Places API" in front of them. You need to first go to certain tabs first to find these options. Also the API key required to start a trial/payment trial. It may be easier for the user, if you created a test API key for everyone to use. I used Mac. When I logged in, i registered an account then when i clicked on the tab "max" it made me login again.

**Comment by jaimenguyen168** [comment]
Thanks you. The lastest Readme has been updated.
