### ISSUE TITLE
Cannot Use Google Login

### ISSUE THREAD

**Issue by HarrryHe** [cis3296f24/Locally#36]
I wanted to create an account using google so I don't need to create extra account, but it doesn't work. Also, the keyboard always shown on the screen so it is super hard to click register or other button because they get blocked by the keyboard. After I logged in, the UI looks pretty good, and I can see the event around Philadelphia at my area. But for the nav bar at the bottom there is a Luis navlink and Maxwell navlink the hyperlink does not work. Overall, the app idea looks pretty good. Just need to improve a litle bit more (Windows: for open up the code and IOS: for scanning the QR code)

**Comment by jaimenguyen168** [comment]
Thank you for your feedback. We don't have the sign-in with Google yet but it will be implemented soon.
