### ISSUE TITLE
Cannot sign up, cannot open without sign in

### ISSUE THREAD

**Issue by JayTSXF** [cis3296f24/Locally#37]
The process turned out to be overly complicated due to the sign-up requirements. After cloning the repository and running the commands, I encountered a QR code in the terminal. Scanning it required downloading the Expo Go app, which I thought would resolve the issue. However, the app couldn’t be opened without signing in, and despite multiple attempts, I was unable to create an account. This made it impossible to proceed, as the app wouldn’t function without a successful sign-in.

I used Windows.

**Comment by jaimenguyen168** [comment]
Hi. You can use accounts to log in here
https://docs.google.com/document/d/1bepWv1b0VqB63SfvTeV4UX-UDuomuCF0q9mVa0vVFEE/edit?tab=t.0
