### ISSUE TITLE
Metdata Page Padding Offcentered

### ISSUE THREAD

**Issue by M-Phuykong** [cis3296f24/Locally#50]
I believe the padding is off in the metadata page. I have attached the screenshot below. 
<img width="430" alt="Screenshot 2024-12-04 at 6 02 22 PM" src="https://github.com/user-attachments/assets/b150e606-c19f-4252-880e-f62928a4a74f">

**Comment by jaimenguyen168** [comment]
Thank you. It'll be fixed in the next release.
